### ISSUE TITLE
Pines se achican

### ISSUE THREAD

**Issue by agustinkry** [datauy/front-end-birra#1]
En la seccion mapa cuando presiono un pin y lo dejo activo luego cambia de tamaño , queda muy chico

**Comment by HiroAgustin** [comment]
No puedo reproducirlo. Los iconos quedan del mismo tamaño en Chrome iPhone 6.

**Comment by agustinkry** [comment]
https://files.slack.com/files-pri/T03JU20UT-F086HAWJ0/cuando_marc___un_pin_luego_me_queda_enano.png

**Comment by HiroAgustin** [comment]
En la foto están del mismo tamaño…

**Comment by HiroAgustin** [comment]
Reproducible en IOS Safari.

**Comment by HiroAgustin** [comment]
Desktop Safari tambien. Parecería ser un problema con el cache de las imagenes svg.

**Comment by EmilioCristalli** [comment]
Debería estar solucionado en el commit 77b5e33 pasando los SVG de los iconos a png. 
Si te sigue dando problemas reabrilo @agustinkry (podes probar en http://dondepinta.uy/)
